Feature
disc3110/MembersOnly pull request #1
Opened 2021-04-07 20:29 UTC by disc3110

This project is a clubhouse where anyone can see the anonymous post but just singed in members can see who the author is. It's been written using Devise gem

2021-04-07 22:55 UTC, enaburekhan requested changes
# Status: Changes required:hammer::wrench::full_moon:
Hi Diego!
Great job on this project:clap::clap:.

**Major highlights**

- The UI is awesome 
- A signed-in user can create new post and see post's author
- The application has Sign in/Sign out links present in any view of the app

However, we still need to make a few changes to get the project approved:muscle:.
**To improve**

- [ ] As highlighted in the PR below. Kindly edit the readme `title` to reflect the current project. Which is `Members Only. This will make it more descriptive.

- [ ] It creates the application routes using `resources :posts, only: [:new, :create, :index]` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)). Kindly fix this.

- [ ] PostsController

- it uses `before_action` to restrict access to the `:new` and `:create` methods (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)). You can achieve this by creating a similar method like this below in the applicationController helper:

```ruby
def signed_in_only!
  # current_user in ApplicationController must be defined as helper method to make it work
  redirect_to  new_user_session_path unless current_user

  ## alternative solution:
  # if signed_in? is defined in ApplicationController (see stretch requirements)
  redirect_to new_user_session_path unless signed_in?
end
```
Then pass the below at the top of the Post controller:
`before_action :signed_in_only!, only: [:new, :create]`

- it initializes an empty post `@post = Post.new` in the `new` action. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)).

- [ ] As commented in the PR below. Kindly move all the highlighted logic in view to a helper. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) and this [article](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) if you need help on how to use a helper in rails. see [screen-shot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright

**Optional**
- [ ] Kindly add author name to the readme.
- [ ] Please, cultivate the habit of committing messages often when building a project codebase. I expect to see more commit messages when fixing the changes.

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-04-07 22:55 UTC, enaburekhan commented on README.md
> +# Forms - Ruby on Rails
Edit the title to reflect the current project. Which is `Members Only`.

2021-04-07 22:55 UTC, enaburekhan commented on app/controllers/posts_controller.rb
> +    @post = current_user.posts.build
This should be: 
def new
  @post = Post.new
end

2021-04-07 22:55 UTC, enaburekhan commented on app/views/comments/_form.html.erb
> +        <% end %>
Move the logic to a helper. There should be absolutely no logic  in view. Views are only use to render information that became available to them from it's corresponding controller and not for generating it.

2021-04-07 22:55 UTC, enaburekhan commented on app/views/layouts/_header.html.erb
> +        <% end %>
Also move this logic to a helper.

2021-04-07 22:55 UTC, enaburekhan commented on app/views/layouts/application.html.erb
> +    <% end %>
Move this logic to a helper.

2021-04-07 22:55 UTC, enaburekhan commented on app/views/posts/_body.html.erb
> +            <% end %>
Move this logic to a helper.

2021-04-07 22:55 UTC, enaburekhan commented on app/views/posts/_form.html.erb
> +  <% end %>
Move this logic to a helper.

2021-04-07 22:55 UTC, enaburekhan commented on app/views/posts/index.html.erb
> +<% end %>
Move this logic to a helper.

2021-04-07 22:55 UTC, enaburekhan commented on config/routes.rb
> +  root 'posts#index'
The application route should be created with only `resources :posts, only: [:new, :create, :index]`

2021-04-08 19:52 UTC, smcommits requested changes
# Status: Changes Required
## Hello, @disc3110! You have done a great job. Nice work implementing the changes that the previous TSE suggested. This project is almost complete. We just need address one criticl issue

## Required Changes

- [ ] **I cannot create a post. The application breaks. Please fix this**

I am assuming that the changes you made are causing this. Please find the issue and fix this. 
Application Breaks While Creating a Post
:------------------------------------------------------:
![rails-new-createpost](https://user-images.githubusercontent.com/59168430/114087738-ddb2c700-98d1-11eb-8825-6cc36e0e6afc.gif)

# 
## Please reach out to me on Slack if you need assistance or I have overlooked something and made an unfair request.

2021-04-08 20:56 UTC, enaburekhan requested changes
# Status: Changes required:wrench::hammer::full_moon:
**Hi Diego!
Great job so far:clap::clap:. Thank you for implementing almost all the required and optional changes:pray:. We are almost there. We just need to quickly fix one change to get the project approved:muscle:.**

**To improve**

- [ ] As I highlighted in my last review. Pass the `before_action :signed_in_only!, only: [:new, :create]` to the top of the post controller. To restrict access to the `new` and `create` methods. You have already defined the method in the application_helper in the controller. 

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-04-08 23:39 UTC, voscarmv approved these changes
# Project status: Approved 💯 ✨ 😎 👍 

- Great work applying the last remaining details required by the previous code reviewer.

### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

2022-04-11 22:19 UTC, merged